### ISSUE TITLE
GLControl Factory, PlatformNotSupportedException is not supported on this platform

### ISSUE THREAD

**Issue by HIMISOCOOL** [jaquadro/MonoGame-WinFormsControls#1]
```
  class GLControlFactory

        if (Configuration.RunningOnWindows) return new WinGLControl(mode, control);
        else if (Configuration.RunningOnMacOS) return new CarbonGLControl(mode, control);
        else if (Configuration.RunningOnX11) return new X11GLControl(mode, control);
        else throw new PlatformNotSupportedException();//Operation is not supported on this platform.
```

I'm running windows 8 pro any ideas??

**Comment by jaquadro** [comment]
I don't know why RunningOnWindows wouldn't be true.

You could try commenting out the whole if/else block and try returning new WinGLControl(mode, control).  You'll also need to see where else Configuration.RunningOnWindows might be used.

You're only going to be able to run this on Windows anyway.  If the WinGLControl constructor throws then that will require more digging.

**Comment by HIMISOCOOL** [comment]
Okay, thanks I probably should have thought of that but I was programming at 12am or so... but im awake and Im fresh and this literally makes no sense to me

```
 class GraphicsDeviceService : IGraphicsDeviceService
 {
 ....
     private GraphicsDevice _device;
 ....
     protected void CreateDevice (IntPtr windowHandle, int width, int height)
     {
     ....
     _device = new GraphicsDevice(adapter, profile, pp);//NullReferenceException was unhandled, Object reference not set to an instance of an object.
     ....
     }
 }
```

**Comment by jaquadro** [comment]
GraphicsDevice has to be throwing internally.  Reference the MonoGame project directly so you can see just where it breaks.

**Comment by jaquadro** [comment]
This issue is almost a year old, and MonoGame WinForms support has been dead in the water since April 28th, but while investigating that I found why this was probably happening, and checked in a fix to the tree.

I'll be following up on the MonoGame issue in a bit.  Track this issue for more information and a patch/workaround https://github.com/mono/MonoGame/issues/2586
