### ISSUE TITLE
Getting Blackscreen with every example

### ISSUE THREAD

**Issue by Nyankoo** [jaquadro/MonoGame-WinFormsControls#2]
Every example is lunching fine but only displays a black screen. Runs on Windows 7 with MonoGame 3.2.

**Comment by jaquadro** [comment]
The last time I installed a MonoGame 3.2 release (admittedly a few months ago), the DirectX build was getting aliased on top of the WindowsGL build.  Make sure you actually have WindowsGL assemblies installed (verify in ildasm), or build against MonoGame source instead to be sure you've got the right ones.

**Comment by Nyankoo** [comment]
Thanks for the fast reply.
The MonoGame.Framework was referencing Windows 8 and I changed it to WindowsGL.
Now I run in your "ExampleGame.Embedded" example into a NullPointerExecption where the engine is null when I try to change the ball count.
Screen is still black at this point.

**Comment by jaquadro** [comment]
GameControl is in another project - did you update the assemblies in both places?  An exception with _engine null suggests Initialize() was never called.  It points at GLControl itself not initializing correctly.

**Comment by Nyankoo** [comment]
The references to the other projects are set (I didn't change them because they look ok) and I can't find a reason why Initialize() is not called (breakpoint is never reached).

**Comment by jaquadro** [comment]
I meant that you need to update you MonoGame references in all referenced projects, if you have not done so.

**Comment by Nyankoo** [comment]
I hope I understand you (quiet new to all this), but I deleted now all MonoGame.Framework references in every project and replaced them with the windows-ones. For some reason even when I choose the assembly in the Windows directory or the WindowsGL directory it shows the Windows 8 version. Maybe this is a problem?
After changing black screen still there.

**Comment by jaquadro** [comment]
If MonoGameTeam never fixed their packaging bug in the 3.2 installer, then you can't get the WindowsGL assemblies (I think).

I strongly recommend checking out a copy of the MonoGame source, and then building the WindowsGL solution.  Reference the assemblies you build.

**Comment by Nyankoo** [comment]
Ok, I manually added the references to WindowsGL to my projects (don't know why I wasn't thinking of that earlier, sorry) and now I don't get the NullPointerException anymore. I can put the ball count up and down without issues.
But sadly the black screen is still present and I don't see anything else.

**Comment by jaquadro** [comment]
I just tried installing a copy of the latest installer.  The MonoGame.Framework.dll assembly in the Assemblies/WindowsGL is not actually the WindowsGL assembly.  It's a copy of the Windows (DirectX) assembly.  You'll have to build your own copy; the 3.2 installer is broken.

**Comment by Nyankoo** [comment]
I built my own copy of the WindowsGL assembly and finally it works fine.
Thank you for looking into it so much!

**Comment by jaquadro** [comment]
Glad it worked out.

**Comment by jaquadro** [comment]
For the record, I submitted this issue to MonoGame and it's now resolved in the latest 3.2 development build.

**Comment by Nyankoo** [comment]
Great! Really appreciating your work!
